# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
    azureSubscriptionEndpoint: w233
    azureContainerRegistry: mics233.azurecr.io

steps:
  - task: AzureKeyVault@1
    displayName: Get Secrets
    inputs:
        azureSubscription: w233
        keyVaultName: mics-kv
        secretsFilter: '*'

  - task: Docker@1
    displayName: Docker Login
    inputs: 
        command: login
        azureContainerRegistry: $(azureContainerRegistry)
        azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)

  - template: ingress/ingress-build.yml
#  - template: processing/processor-build.yml
  - template: egress/egress-build.yml
