FROM mics233.azurecr.io/rbase

ADD notebooks notebooks

RUN cd notebooks; R -f validateScripts.r

FROM python

ARG databrickstoken
ARG databrickshost
ENV databrickstoken=$databrickstoken
ENV databrickshost=$databrickshost

ADD notebooks notebooks

RUN cd notebooks; pip install requests; python publishnotebooks.py
