steps:
  - task: Docker@1
    displayName: Validate & Build Ingress
    inputs:
      command: build
      dockerfile: $(Build.SourcesDirectory)/ingress/dockerfile
      buildConext: $(Build.SourcesDirectory)/ingress
      arguments: --build-arg ingressconnectionstring=$(ingressconnectionstring)
