
steps: 
  - task: Bash@3
    displayName: Validate & Build Ingress
    inputs:
        targetType: inline
        script: docker build --file="./dockerfile" --build-arg ingressconnectionstring=$(ingressconnectionstring) . 
        workingDirectory: $(Build.SourcesDirectory)/ingress
