
steps: 
  - task: Bash@3
    displayName: Build Ingress Container
    inputs:
        targetType: inline
        #script: docker build -t ingress:$(Build.BuildId) --build-arg ingressconnectionstring=$(ingressconnectionstring) --file="./dockerfile" .
        script: ls  
        workingDirectory: $(Build.SourcesDirectory)/ingress
