
steps: 
  - task: Bash@3
    displayName: Validate & Build Ingress
    inputs:
        targetType: inline
        script: docker build --build-arg ingressconnectionstring=$(ingressconnectionstring) . --file="./dockerfile"
        workingDirectory: $(Build.SourcesDirectory)/ingress
